# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de9702f7d510d012536151cb2a2fdd83be6114ddb50165d4fdeafef9e59e89e704533679842d1166feff863061f8fbe1ab2d1fded8c53d3d2f42f3f50fbff1dd

test:
  secret_key_base: 629edf8c384538536bcd5989ec6d5f4a32f542a3ac45d208b2aea06751542621a6f6786756990acc019d89a44a9ac87616636e393ed8e5b1cd301c41520858c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
